name: Cluster tests (JDK25 & MySQL)

on: [pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up MySQL
        run: |
            sudo /etc/init.d/mysql start
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21.0.4'
      - name: Build in JDK 21
        run: mvn -B clean install -DskipTests --file pom.xml
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Cluster Tests with JDK 25
        run: mvn -B clean install --file integration/pom.xml -P cluster-tests
