name: Smoke Tests (Windows - JDK21)

on: [pull_request]

jobs:
  smoke-tests:

    runs-on: windows-latest
    steps:
      - name: Configure Git to support long paths
        run: git config --global core.longpaths true
      - name: Verify Git configuration for long paths
        run: git config --global core.longpaths
      - uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21.0.4'
      - name: Build with Maven
        run: mvn -B clean install -P smoke-tests --file pom.xml -fae

